[package]
name = "rock_paper_scissors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
bevy_kira_audio = "0.16"
once_cell = "1.18.0"
rand = "0.8.5"