appenders:
  my_file_logger:
    kind: rolling_file
    path: "logs/rock_paper_scissors.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} - {h({l})}: {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        base: 1
        count: 10
        pattern: "logs/rock_paper_scissors_{}.log"
root:
  level: debug
  appenders:
    - my_file_logger